#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LatihanListView.Resource", IsApplication=true)]

namespace LatihanListView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int makanan = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int search = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int btnExpandableListView = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int btnListView = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int btnListViewCustom = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int expandLV = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int hargaTextView = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int item_icon = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int lblLvHeader = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int makananListView = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int makananTextView = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int tanggalTextView = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int customRowListView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ExpandableListViewLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HeaderExpandLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListViewLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
