#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LatihanRecyclerView.Resource", IsApplication=true)]

namespace LatihanRecyclerView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int cardBackgroundColor = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int cardCornerRadius = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int cardElevation = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int cardMaxElevation = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public const int cardPreventCornerOverlap = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int cardUseCompatPadding = 2130771981;
			
			// aapt resource value: 0x7f01000f
			public const int contentPadding = 2130771983;
			
			// aapt resource value: 0x7f010013
			public const int contentPaddingBottom = 2130771987;
			
			// aapt resource value: 0x7f010010
			public const int contentPaddingLeft = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int contentPaddingRight = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int contentPaddingTop = 2130771986;
			
			// aapt resource value: 0x7f010004
			public const int fastScrollEnabled = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fastScrollHorizontalThumbDrawable = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fastScrollHorizontalTrackDrawable = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int fastScrollVerticalThumbDrawable = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int fastScrollVerticalTrackDrawable = 2130771974;
			
			// aapt resource value: 0x7f01001b
			public const int font = 2130771995;
			
			// aapt resource value: 0x7f010014
			public const int fontProviderAuthority = 2130771988;
			
			// aapt resource value: 0x7f010017
			public const int fontProviderCerts = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int fontProviderFetchStrategy = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int fontProviderFetchTimeout = 2130771993;
			
			// aapt resource value: 0x7f010015
			public const int fontProviderPackage = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int fontProviderQuery = 2130771990;
			
			// aapt resource value: 0x7f01001a
			public const int fontStyle = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public const int fontWeight = 2130771996;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0a0000
			public const int abc_action_bar_embed_tabs = 2131361792;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int cardview_dark_background = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_light_background = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_shadow_end_color = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int cardview_shadow_start_color = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int notification_action_color_filter = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int notification_icon_bg_color = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int notification_material_background_media_default_color = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int primary_text_default_material_dark = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int ripple_material_light = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int secondary_text_default_material_dark = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int secondary_text_default_material_light = 2131165194;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040006
			public const int cardview_compat_inset_shadow = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int cardview_default_elevation = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int cardview_default_radius = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int compat_button_inset_horizontal_material = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int compat_button_inset_vertical_material = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int compat_button_padding_horizontal_material = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int compat_button_padding_vertical_material = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int compat_control_corner_material = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int fastscroll_default_thickness = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fastscroll_margin = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fastscroll_minimum_range = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int item_touch_helper_swipe_escape_velocity = 2130968581;
			
			// aapt resource value: 0x7f040012
			public const int notification_action_icon_size = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int notification_action_text_size = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int notification_big_circle_margin = 2130968596;
			
			// aapt resource value: 0x7f04000a
			public const int notification_content_margin_start = 2130968586;
			
			// aapt resource value: 0x7f040015
			public const int notification_large_icon_height = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int notification_large_icon_width = 2130968598;
			
			// aapt resource value: 0x7f04000b
			public const int notification_main_column_padding_top = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_media_narrow_margin = 2130968588;
			
			// aapt resource value: 0x7f040017
			public const int notification_right_icon_size = 2130968599;
			
			// aapt resource value: 0x7f040009
			public const int notification_right_side_padding_top = 2130968585;
			
			// aapt resource value: 0x7f040018
			public const int notification_small_icon_background_padding = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int notification_small_icon_size_as_large = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int notification_subtext_size = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int notification_top_pad = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int notification_top_pad_large_text = 2130968604;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f020010
			public const int notification_template_icon_bg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int notification_template_icon_low_bg = 2130837521;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int product1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int product2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int product3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int product4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int product5 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int search = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050014
			public const int action0 = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int action_container = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int action_divider = 2131034136;
			
			// aapt resource value: 0x7f050012
			public const int action_image = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int action_text = 2131034131;
			
			// aapt resource value: 0x7f050022
			public const int actions = 2131034146;
			
			// aapt resource value: 0x7f050007
			public const int async = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int blocking = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int btnLayout = 2131034127;
			
			// aapt resource value: 0x7f050015
			public const int cancel_action = 2131034133;
			
			// aapt resource value: 0x7f05001d
			public const int chronometer = 2131034141;
			
			// aapt resource value: 0x7f050024
			public const int end_padder = 2131034148;
			
			// aapt resource value: 0x7f050009
			public const int forever = 2131034121;
			
			// aapt resource value: 0x7f05001f
			public const int icon = 2131034143;
			
			// aapt resource value: 0x7f050023
			public const int icon_group = 2131034147;
			
			// aapt resource value: 0x7f05000c
			public const int imgView = 2131034124;
			
			// aapt resource value: 0x7f05001e
			public const int info = 2131034142;
			
			// aapt resource value: 0x7f05000a
			public const int italic = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int lblTitle = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int line1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int line3 = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int main_content = 2131034126;
			
			// aapt resource value: 0x7f050017
			public const int media_actions = 2131034135;
			
			// aapt resource value: 0x7f05000b
			public const int normal = 2131034123;
			
			// aapt resource value: 0x7f050021
			public const int notification_background = 2131034145;
			
			// aapt resource value: 0x7f05001a
			public const int notification_main_column = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int notification_main_column_container = 2131034137;
			
			// aapt resource value: 0x7f050010
			public const int rcView = 2131034128;
			
			// aapt resource value: 0x7f050020
			public const int right_icon = 2131034144;
			
			// aapt resource value: 0x7f05001b
			public const int right_side = 2131034139;
			
			// aapt resource value: 0x7f050016
			public const int status_bar_latest_event_content = 2131034134;
			
			// aapt resource value: 0x7f050003
			public const int tag_transition_group = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int text = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int text2 = 2131034117;
			
			// aapt resource value: 0x7f05001c
			public const int time = 2131034140;
			
			// aapt resource value: 0x7f050006
			public const int title = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int cancel_button_image_alpha = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int status_bar_notification_info_maxnum = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CardViewLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_action_tombstone = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_media_action = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_media_cancel_action = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_big_media = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_big_media_custom = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_big_media_narrow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_big_media_narrow_custom = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_custom_big = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_icon_group = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_lines_media = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_media = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_media_custom = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_part_chronometer = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_part_time = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int status_bar_notification_info_overflow = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Base_CardView = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int CardView = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int CardView_Light = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int TextAppearance_Compat_Notification = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int TextAppearance_Compat_Notification_Info = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int TextAppearance_Compat_Notification_Info_Media = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int TextAppearance_Compat_Notification_Line2 = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int TextAppearance_Compat_Notification_Media = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int TextAppearance_Compat_Notification_Time = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int TextAppearance_Compat_Notification_Time_Media = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int TextAppearance_Compat_Notification_Title = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int TextAppearance_Compat_Notification_Title_Media = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int Widget_Compat_NotificationActionContainer = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int Widget_Compat_NotificationActionText = 2131099662;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] FontFamily = new int[] {
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollEnabled = 6;
			
			// aapt resource value: 9
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 10;
			
			// aapt resource value: 7
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 8;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
